# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pytest NASA API (EPIC tests)

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

permissions:
  contents: read

jobs:
  build:
    name: end2end
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    # Setup Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run pytest tests
    - name: Test with pytest
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        pytest tests/epic_tests.py --html=results/report.html --self-contained-html

    # Step to save log file to the artifacts directory
    - name: Save log file to artifacts
      run: cp tests/logs/output.log $GITHUB_WORKSPACE/results/output.log

    # Set $GITHUB_WORKSPACE variable
    - name: Set output
      if: always()
      id: results
      run: echo "artifactPath=results/" >> $GITHUB_OUTPUT

    # Upload artifacts
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report
        path: ${{ steps.results.outputs.artifactPath }}